### ISSUE TITLE
AC_CHECK_LIB([lwgrp], [GCS_Comm_split])

### ISSUE THREAD

**Issue by brianjmurrell** [LLNL/dtcmp#6]
I am noticing the search for `GCS_Comm_split()` as the "is it present" function in the (yes, commented out) autotools test https://github.com/LLNL/dtcmp/blob/8b5b50b845a61415e53ba2dde20a5f67cc33e6a5/m4/x_ac_lwgrp.m4#L50 added in 8b5b50b845a61415e53ba2dde20a5f67cc33e6a5.

However even in 8b5b50b845a61415e53ba2dde20a5f67cc33e6a5 I don't see that function in the source.

What am I missing (beyond the test being commented out)?  Was `GCS_Comm_split()` ever a function in this library?

**Comment by adammoody** [comment]
Good eye!  There was a "Generalized Comm Split" (GCS) library before lwgrp existed.  We should be able to remove that particular ``AC_CHECK_LIB`` macro and related m4 code.

Were you looking for GCS_Comm_split or just wondering why those stray checks are in there?

**Comment by brianjmurrell** [comment]
I don't think removing it is the right fix.  Without it, an openmpi3 built lwgrp, according to RedHat's multi-mpi stack support methodology, is not discoverable by dtcmp.

I've created #7 to fix this.  With this patch, lwgrp built according to RedHat's multi-mpi stack methodology is discoverable by `configure`.

**Comment by adammoody** [comment]
Yes, I see what you meant now.  Thanks for the fix.

**Comment by adammoody** [comment]
Given that you're working through some build configurations that are apparently not well tested, do you think you'll have more patches on the way?  I can hold off on the point release to roll them all up in one if that's the case.  Just let me know.

**Comment by brianjmurrell** [comment]
Thanks for checking in.  I don't think I will have any more build patches for this project at the moment.  I seem to have gotten my build to work with #7.
